try:
    raise Exception("some exception")
except:
    print('got an exception')